services:
  app:
    user: root
    entrypoint:
    - sleep
    - infinity
    image: rianfowler/glowing-system-dev-env:latest
    pull_policy: always
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
