name: "latest-prerelease"
version: "0.0.3"
usage: "Get the latest pre-release version of a Helm chart"
description: "A Helm plugin to fetch the latest pre-release version of a specified chart"
ignoreFlags: false
command: "bin/plugin.sh"
